/* eslint import/no-anonymous-default-export: [2, {"allowObject": true}] */
export default {
    //WebDriver Command

    //Browser Command
    getCommand: "get(String arg0): void | driver.get(appUrl)",
    GetTitleCommand: "getTitle(): String | driver.getTitle()",
    GetCurrentURLCommand: "getCurrentUrl(): String | driver.getCurrentUrl()",
    GetPageSourceCommand: "getPageSource(): String | getPageSource(): String",
    CloseCommand: "close(): void | close(): void ",
    QuitCommand: "quit(): void | driver.quit()",

    //Navigation Command
    NavigateToCommand : "to(String arg0) : void | driver.navigate().to(appUrl)",
    ForwardCommand: "forward() : void | driver.navigate().forward()",
    BackCommand: "back() : void | driver.navigate().back()",
    RefreshCommand: "refresh() : void  | driver.navigate().refresh()",
    
    //WebElement Command - WebElement element = driver.findElement(By.id(“UserName“));
    //WebElement can be of any type, like it can be a Text, Link, Radio Button, Drop Down, WebTable or any HTML element
    ClearCommand: "clear( ) : void | element.clear()",
    SendKeysCommand: "sendKeys(CharSequence… keysToSend ) : void | element.sendKeys(“text”)",
    ClickCommand: "click( ) : void | click( ) : void",
    IsDisplayedCommand: "isDisplayed( ) : boolean | element.isDisplayed()",
    IsEnabledCommand: "isEnabled( ) : boolean | element.isEnabled()",
    IsSelectedCommand: "isSelected( ) : boolean | element.isSelected()",
    SubmitCommand: "submit( ) : void | element.submit()",
    GetTextCommand: "getText( ) : String | element.getText()",
    getTagNameCommand: "getTagName( ) : String | element.getTagName()",
    getCssValueCommand: "getCssvalue( ) : String | element.getCssValue()",
    getAttributeCommand: "getAttribute(String Name) : String | element.getAttribute();",
    getSizeCommand: "getSize( ) : Dimension | element.getSize()",
    getLocationCommand: "getLocation( ) : Point | element.getLocation()",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",
    b: "",





}