// Server component wrapper for generateStaticParams
import PracticePageClient from './PracticePageClient'

// Generate static params for static export (must be in server component)
export function generateStaticParams() {
  return [
    // Tab routes
    { slug: 'examples' },
    { slug: 'hands-on-practical-exam' },
    { slug: 'testcases' },
    { slug: 'quiz' },
    { slug: 'scorecard' },
    // Practice sub-pages
    { slug: 'ab-testing' },
    { slug: 'add-remove-elements' },
    { slug: 'basic-auth' },
    { slug: 'broken-images' },
    { slug: 'challenging-dom' },
    { slug: 'checkboxes' },
    { slug: 'context-menu' },
    { slug: 'digest-auth' },
    { slug: 'disappearing-elements' },
    { slug: 'drag-and-drop' },
    { slug: 'dropdown' },
    { slug: 'dynamic-content' },
    { slug: 'dynamic-controls' },
    { slug: 'dynamic-loading' },
    { slug: 'entry-ad' },
    { slug: 'exit-intent' },
    { slug: 'file-download' },
    { slug: 'file-upload' },
    { slug: 'floating-menu' },
    { slug: 'forgot-password' },
    { slug: 'form-authentication' },
    { slug: 'frames' },
    { slug: 'geolocation' },
    { slug: 'horizontal-slider' },
    { slug: 'hovers' },
    { slug: 'infinite-scroll' },
    { slug: 'inputs' },
    { slug: 'jquery-ui-menus' },
    { slug: 'javascript-alerts' },
    { slug: 'javascript-error' },
    { slug: 'key-presses' },
    { slug: 'large-deep-dom' },
    { slug: 'multiple-windows' },
    { slug: 'nested-frames' },
    { slug: 'notification-messages' },
    { slug: 'redirect-link' },
    { slug: 'registration-form' },
    { slug: 'e2e-flow' },
    { slug: 'playwright-sandbox' },
    { slug: 'playwright-syntax' },
    { slug: 'secure-file-download' },
    { slug: 'shadow-dom' },
    { slug: 'shifting-content' },
    { slug: 'slow-resources' },
    { slug: 'sortable-data-tables' },
    { slug: 'status-codes' },
    { slug: 'typos' },
    { slug: 'wysiwyg-editor' },
    { slug: 'api-examples' },
    { slug: 'performance-examples' },
    { slug: 'python-examples' },
    { slug: 'python-intro' },
    { slug: 'python-variables-data-types' },
    { slug: 'python-operators-expressions' },
    { slug: 'python-conditional-statements' },
    { slug: 'python-loops' },
    { slug: 'python-strings' },
    { slug: 'python-lists-tuples' },
    { slug: 'python-dictionaries-sets' },
    { slug: 'python-functions' },
    { slug: 'python-advanced-functions' },
    { slug: 'python-modules-packages' },
    { slug: 'python-file-handling' },
    { slug: 'python-exception-handling' },
    { slug: 'python-oop-part1' },
    { slug: 'python-oop-part2' },
    { slug: 'python-mini-project-1' },
    { slug: 'python-json-csv' },
    { slug: 'python-apis' },
    { slug: 'python-sqlite' },
    { slug: 'python-git-github' },
    { slug: 'python-debugging-testing' },
    { slug: 'python-automation' },
    { slug: 'python-problem-solving' },
    { slug: 'python-mini-project-2' },
    { slug: 'python-intro-data-science' },
    { slug: 'python-numpy' },
    { slug: 'python-pandas-part1' },
    { slug: 'python-pandas-part2' },
    { slug: 'python-data-visualization' },
    { slug: 'python-advanced-data-analysis' },
    { slug: 'python-intro-ml' },
    { slug: 'python-scikit-learn' },
    { slug: 'python-intro-cyber-security' },
    { slug: 'python-log-analysis' },
    { slug: 'python-networking-basics' },
    { slug: 'python-security-scripting' },
    { slug: 'python-regex-security' },
    { slug: 'python-hashing-cryptography' },
    { slug: 'python-api-security' },
    { slug: 'python-cyber-mini-project' },
    { slug: 'python-advanced-concepts' },
    { slug: 'python-clean-code' },
    { slug: 'python-career-project-ds' },
    { slug: 'python-career-project-cyber' },
    { slug: 'python-capstone' },
    { slug: 'python-final-presentation' },
    { slug: 'python-career-readiness' },
    { slug: 'appium-ios-emulator' },
    { slug: 'appium-android-emulator' },
    { slug: 'appium-ios-device' },
    { slug: 'appium-android-device' },
  ]
}

export default function PracticeSlugPage() {
  return <PracticePageClient />
}
